/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CorretorRouteImport } from './routes/corretor'
import { Route as CorrespondenteRouteImport } from './routes/correspondente'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CorretorIndexRouteImport } from './routes/corretor.index'
import { Route as CorrespondenteIndexRouteImport } from './routes/correspondente.index'
import { Route as ClienteIndexRouteImport } from './routes/cliente.index'
import { Route as CorretorOperacionalRouteImport } from './routes/corretor.operacional'
import { Route as CorretorCrmRouteImport } from './routes/corretor.crm'
import { Route as CorrespondenteOperacionalRouteImport } from './routes/correspondente.operacional'
import { Route as CorrespondenteCrmRouteImport } from './routes/correspondente.crm'
import { Route as CorretorOperacionalIndexRouteImport } from './routes/corretor.operacional.index'
import { Route as CorretorCrmIndexRouteImport } from './routes/corretor.crm.index'
import { Route as CorrespondenteOperacionalIndexRouteImport } from './routes/correspondente.operacional.index'
import { Route as CorrespondenteCrmIndexRouteImport } from './routes/correspondente.crm.index'
import { Route as CorretorOperacionalSimulacoesRouteImport } from './routes/corretor.operacional.simulacoes'
import { Route as CorretorOperacionalMinhasSimulacoesRouteImport } from './routes/corretor.operacional.minhas-simulacoes'
import { Route as CorretorOperacionalConsultasRouteImport } from './routes/corretor.operacional.consultas'
import { Route as CorretorCrmRelatoriosRouteImport } from './routes/corretor.crm.relatorios'
import { Route as CorretorCrmConsultasRouteImport } from './routes/corretor.crm.consultas'
import { Route as CorretorCrmCadastroRouteImport } from './routes/corretor.crm.cadastro'
import { Route as CorrespondenteOperacionalSimulacoesRouteImport } from './routes/correspondente.operacional.simulacoes'
import { Route as CorrespondenteOperacionalMinhasSimulacoesRouteImport } from './routes/correspondente.operacional.minhas-simulacoes'
import { Route as CorrespondenteOperacionalConsultasRouteImport } from './routes/correspondente.operacional.consultas'
import { Route as CorrespondenteCrmRelatoriosRouteImport } from './routes/correspondente.crm.relatorios'
import { Route as CorrespondenteCrmConsultasRouteImport } from './routes/correspondente.crm.consultas'
import { Route as CorrespondenteCrmCadastroRouteImport } from './routes/correspondente.crm.cadastro'

const CorretorRoute = CorretorRouteImport.update({
  id: '/corretor',
  path: '/corretor',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrespondenteRoute = CorrespondenteRouteImport.update({
  id: '/correspondente',
  path: '/correspondente',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CorretorIndexRoute = CorretorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CorretorRoute,
} as any)
const CorrespondenteIndexRoute = CorrespondenteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CorrespondenteRoute,
} as any)
const ClienteIndexRoute = ClienteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClienteRoute,
} as any)
const CorretorOperacionalRoute = CorretorOperacionalRouteImport.update({
  id: '/operacional',
  path: '/operacional',
  getParentRoute: () => CorretorRoute,
} as any)
const CorretorCrmRoute = CorretorCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => CorretorRoute,
} as any)
const CorrespondenteOperacionalRoute =
  CorrespondenteOperacionalRouteImport.update({
    id: '/operacional',
    path: '/operacional',
    getParentRoute: () => CorrespondenteRoute,
  } as any)
const CorrespondenteCrmRoute = CorrespondenteCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => CorrespondenteRoute,
} as any)
const CorretorOperacionalIndexRoute =
  CorretorOperacionalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CorretorOperacionalRoute,
  } as any)
const CorretorCrmIndexRoute = CorretorCrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CorretorCrmRoute,
} as any)
const CorrespondenteOperacionalIndexRoute =
  CorrespondenteOperacionalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CorrespondenteOperacionalRoute,
  } as any)
const CorrespondenteCrmIndexRoute = CorrespondenteCrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CorrespondenteCrmRoute,
} as any)
const CorretorOperacionalSimulacoesRoute =
  CorretorOperacionalSimulacoesRouteImport.update({
    id: '/simulacoes',
    path: '/simulacoes',
    getParentRoute: () => CorretorOperacionalRoute,
  } as any)
const CorretorOperacionalMinhasSimulacoesRoute =
  CorretorOperacionalMinhasSimulacoesRouteImport.update({
    id: '/minhas-simulacoes',
    path: '/minhas-simulacoes',
    getParentRoute: () => CorretorOperacionalRoute,
  } as any)
const CorretorOperacionalConsultasRoute =
  CorretorOperacionalConsultasRouteImport.update({
    id: '/consultas',
    path: '/consultas',
    getParentRoute: () => CorretorOperacionalRoute,
  } as any)
const CorretorCrmRelatoriosRoute = CorretorCrmRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => CorretorCrmRoute,
} as any)
const CorretorCrmConsultasRoute = CorretorCrmConsultasRouteImport.update({
  id: '/consultas',
  path: '/consultas',
  getParentRoute: () => CorretorCrmRoute,
} as any)
const CorretorCrmCadastroRoute = CorretorCrmCadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => CorretorCrmRoute,
} as any)
const CorrespondenteOperacionalSimulacoesRoute =
  CorrespondenteOperacionalSimulacoesRouteImport.update({
    id: '/simulacoes',
    path: '/simulacoes',
    getParentRoute: () => CorrespondenteOperacionalRoute,
  } as any)
const CorrespondenteOperacionalMinhasSimulacoesRoute =
  CorrespondenteOperacionalMinhasSimulacoesRouteImport.update({
    id: '/minhas-simulacoes',
    path: '/minhas-simulacoes',
    getParentRoute: () => CorrespondenteOperacionalRoute,
  } as any)
const CorrespondenteOperacionalConsultasRoute =
  CorrespondenteOperacionalConsultasRouteImport.update({
    id: '/consultas',
    path: '/consultas',
    getParentRoute: () => CorrespondenteOperacionalRoute,
  } as any)
const CorrespondenteCrmRelatoriosRoute =
  CorrespondenteCrmRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => CorrespondenteCrmRoute,
  } as any)
const CorrespondenteCrmConsultasRoute =
  CorrespondenteCrmConsultasRouteImport.update({
    id: '/consultas',
    path: '/consultas',
    getParentRoute: () => CorrespondenteCrmRoute,
  } as any)
const CorrespondenteCrmCadastroRoute =
  CorrespondenteCrmCadastroRouteImport.update({
    id: '/cadastro',
    path: '/cadastro',
    getParentRoute: () => CorrespondenteCrmRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cliente': typeof ClienteRouteWithChildren
  '/correspondente': typeof CorrespondenteRouteWithChildren
  '/corretor': typeof CorretorRouteWithChildren
  '/correspondente/crm': typeof CorrespondenteCrmRouteWithChildren
  '/correspondente/operacional': typeof CorrespondenteOperacionalRouteWithChildren
  '/corretor/crm': typeof CorretorCrmRouteWithChildren
  '/corretor/operacional': typeof CorretorOperacionalRouteWithChildren
  '/cliente/': typeof ClienteIndexRoute
  '/correspondente/': typeof CorrespondenteIndexRoute
  '/corretor/': typeof CorretorIndexRoute
  '/correspondente/crm/cadastro': typeof CorrespondenteCrmCadastroRoute
  '/correspondente/crm/consultas': typeof CorrespondenteCrmConsultasRoute
  '/correspondente/crm/relatorios': typeof CorrespondenteCrmRelatoriosRoute
  '/correspondente/operacional/consultas': typeof CorrespondenteOperacionalConsultasRoute
  '/correspondente/operacional/minhas-simulacoes': typeof CorrespondenteOperacionalMinhasSimulacoesRoute
  '/correspondente/operacional/simulacoes': typeof CorrespondenteOperacionalSimulacoesRoute
  '/corretor/crm/cadastro': typeof CorretorCrmCadastroRoute
  '/corretor/crm/consultas': typeof CorretorCrmConsultasRoute
  '/corretor/crm/relatorios': typeof CorretorCrmRelatoriosRoute
  '/corretor/operacional/consultas': typeof CorretorOperacionalConsultasRoute
  '/corretor/operacional/minhas-simulacoes': typeof CorretorOperacionalMinhasSimulacoesRoute
  '/corretor/operacional/simulacoes': typeof CorretorOperacionalSimulacoesRoute
  '/correspondente/crm/': typeof CorrespondenteCrmIndexRoute
  '/correspondente/operacional/': typeof CorrespondenteOperacionalIndexRoute
  '/corretor/crm/': typeof CorretorCrmIndexRoute
  '/corretor/operacional/': typeof CorretorOperacionalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cliente': typeof ClienteIndexRoute
  '/correspondente': typeof CorrespondenteIndexRoute
  '/corretor': typeof CorretorIndexRoute
  '/correspondente/crm/cadastro': typeof CorrespondenteCrmCadastroRoute
  '/correspondente/crm/consultas': typeof CorrespondenteCrmConsultasRoute
  '/correspondente/crm/relatorios': typeof CorrespondenteCrmRelatoriosRoute
  '/correspondente/operacional/consultas': typeof CorrespondenteOperacionalConsultasRoute
  '/correspondente/operacional/minhas-simulacoes': typeof CorrespondenteOperacionalMinhasSimulacoesRoute
  '/correspondente/operacional/simulacoes': typeof CorrespondenteOperacionalSimulacoesRoute
  '/corretor/crm/cadastro': typeof CorretorCrmCadastroRoute
  '/corretor/crm/consultas': typeof CorretorCrmConsultasRoute
  '/corretor/crm/relatorios': typeof CorretorCrmRelatoriosRoute
  '/corretor/operacional/consultas': typeof CorretorOperacionalConsultasRoute
  '/corretor/operacional/minhas-simulacoes': typeof CorretorOperacionalMinhasSimulacoesRoute
  '/corretor/operacional/simulacoes': typeof CorretorOperacionalSimulacoesRoute
  '/correspondente/crm': typeof CorrespondenteCrmIndexRoute
  '/correspondente/operacional': typeof CorrespondenteOperacionalIndexRoute
  '/corretor/crm': typeof CorretorCrmIndexRoute
  '/corretor/operacional': typeof CorretorOperacionalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cliente': typeof ClienteRouteWithChildren
  '/correspondente': typeof CorrespondenteRouteWithChildren
  '/corretor': typeof CorretorRouteWithChildren
  '/correspondente/crm': typeof CorrespondenteCrmRouteWithChildren
  '/correspondente/operacional': typeof CorrespondenteOperacionalRouteWithChildren
  '/corretor/crm': typeof CorretorCrmRouteWithChildren
  '/corretor/operacional': typeof CorretorOperacionalRouteWithChildren
  '/cliente/': typeof ClienteIndexRoute
  '/correspondente/': typeof CorrespondenteIndexRoute
  '/corretor/': typeof CorretorIndexRoute
  '/correspondente/crm/cadastro': typeof CorrespondenteCrmCadastroRoute
  '/correspondente/crm/consultas': typeof CorrespondenteCrmConsultasRoute
  '/correspondente/crm/relatorios': typeof CorrespondenteCrmRelatoriosRoute
  '/correspondente/operacional/consultas': typeof CorrespondenteOperacionalConsultasRoute
  '/correspondente/operacional/minhas-simulacoes': typeof CorrespondenteOperacionalMinhasSimulacoesRoute
  '/correspondente/operacional/simulacoes': typeof CorrespondenteOperacionalSimulacoesRoute
  '/corretor/crm/cadastro': typeof CorretorCrmCadastroRoute
  '/corretor/crm/consultas': typeof CorretorCrmConsultasRoute
  '/corretor/crm/relatorios': typeof CorretorCrmRelatoriosRoute
  '/corretor/operacional/consultas': typeof CorretorOperacionalConsultasRoute
  '/corretor/operacional/minhas-simulacoes': typeof CorretorOperacionalMinhasSimulacoesRoute
  '/corretor/operacional/simulacoes': typeof CorretorOperacionalSimulacoesRoute
  '/correspondente/crm/': typeof CorrespondenteCrmIndexRoute
  '/correspondente/operacional/': typeof CorrespondenteOperacionalIndexRoute
  '/corretor/crm/': typeof CorretorCrmIndexRoute
  '/corretor/operacional/': typeof CorretorOperacionalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cliente'
    | '/correspondente'
    | '/corretor'
    | '/correspondente/crm'
    | '/correspondente/operacional'
    | '/corretor/crm'
    | '/corretor/operacional'
    | '/cliente/'
    | '/correspondente/'
    | '/corretor/'
    | '/correspondente/crm/cadastro'
    | '/correspondente/crm/consultas'
    | '/correspondente/crm/relatorios'
    | '/correspondente/operacional/consultas'
    | '/correspondente/operacional/minhas-simulacoes'
    | '/correspondente/operacional/simulacoes'
    | '/corretor/crm/cadastro'
    | '/corretor/crm/consultas'
    | '/corretor/crm/relatorios'
    | '/corretor/operacional/consultas'
    | '/corretor/operacional/minhas-simulacoes'
    | '/corretor/operacional/simulacoes'
    | '/correspondente/crm/'
    | '/correspondente/operacional/'
    | '/corretor/crm/'
    | '/corretor/operacional/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cliente'
    | '/correspondente'
    | '/corretor'
    | '/correspondente/crm/cadastro'
    | '/correspondente/crm/consultas'
    | '/correspondente/crm/relatorios'
    | '/correspondente/operacional/consultas'
    | '/correspondente/operacional/minhas-simulacoes'
    | '/correspondente/operacional/simulacoes'
    | '/corretor/crm/cadastro'
    | '/corretor/crm/consultas'
    | '/corretor/crm/relatorios'
    | '/corretor/operacional/consultas'
    | '/corretor/operacional/minhas-simulacoes'
    | '/corretor/operacional/simulacoes'
    | '/correspondente/crm'
    | '/correspondente/operacional'
    | '/corretor/crm'
    | '/corretor/operacional'
  id:
    | '__root__'
    | '/'
    | '/cliente'
    | '/correspondente'
    | '/corretor'
    | '/correspondente/crm'
    | '/correspondente/operacional'
    | '/corretor/crm'
    | '/corretor/operacional'
    | '/cliente/'
    | '/correspondente/'
    | '/corretor/'
    | '/correspondente/crm/cadastro'
    | '/correspondente/crm/consultas'
    | '/correspondente/crm/relatorios'
    | '/correspondente/operacional/consultas'
    | '/correspondente/operacional/minhas-simulacoes'
    | '/correspondente/operacional/simulacoes'
    | '/corretor/crm/cadastro'
    | '/corretor/crm/consultas'
    | '/corretor/crm/relatorios'
    | '/corretor/operacional/consultas'
    | '/corretor/operacional/minhas-simulacoes'
    | '/corretor/operacional/simulacoes'
    | '/correspondente/crm/'
    | '/correspondente/operacional/'
    | '/corretor/crm/'
    | '/corretor/operacional/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClienteRoute: typeof ClienteRouteWithChildren
  CorrespondenteRoute: typeof CorrespondenteRouteWithChildren
  CorretorRoute: typeof CorretorRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/corretor': {
      id: '/corretor'
      path: '/corretor'
      fullPath: '/corretor'
      preLoaderRoute: typeof CorretorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/correspondente': {
      id: '/correspondente'
      path: '/correspondente'
      fullPath: '/correspondente'
      preLoaderRoute: typeof CorrespondenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corretor/': {
      id: '/corretor/'
      path: '/'
      fullPath: '/corretor/'
      preLoaderRoute: typeof CorretorIndexRouteImport
      parentRoute: typeof CorretorRoute
    }
    '/correspondente/': {
      id: '/correspondente/'
      path: '/'
      fullPath: '/correspondente/'
      preLoaderRoute: typeof CorrespondenteIndexRouteImport
      parentRoute: typeof CorrespondenteRoute
    }
    '/cliente/': {
      id: '/cliente/'
      path: '/'
      fullPath: '/cliente/'
      preLoaderRoute: typeof ClienteIndexRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/corretor/operacional': {
      id: '/corretor/operacional'
      path: '/operacional'
      fullPath: '/corretor/operacional'
      preLoaderRoute: typeof CorretorOperacionalRouteImport
      parentRoute: typeof CorretorRoute
    }
    '/corretor/crm': {
      id: '/corretor/crm'
      path: '/crm'
      fullPath: '/corretor/crm'
      preLoaderRoute: typeof CorretorCrmRouteImport
      parentRoute: typeof CorretorRoute
    }
    '/correspondente/operacional': {
      id: '/correspondente/operacional'
      path: '/operacional'
      fullPath: '/correspondente/operacional'
      preLoaderRoute: typeof CorrespondenteOperacionalRouteImport
      parentRoute: typeof CorrespondenteRoute
    }
    '/correspondente/crm': {
      id: '/correspondente/crm'
      path: '/crm'
      fullPath: '/correspondente/crm'
      preLoaderRoute: typeof CorrespondenteCrmRouteImport
      parentRoute: typeof CorrespondenteRoute
    }
    '/corretor/operacional/': {
      id: '/corretor/operacional/'
      path: '/'
      fullPath: '/corretor/operacional/'
      preLoaderRoute: typeof CorretorOperacionalIndexRouteImport
      parentRoute: typeof CorretorOperacionalRoute
    }
    '/corretor/crm/': {
      id: '/corretor/crm/'
      path: '/'
      fullPath: '/corretor/crm/'
      preLoaderRoute: typeof CorretorCrmIndexRouteImport
      parentRoute: typeof CorretorCrmRoute
    }
    '/correspondente/operacional/': {
      id: '/correspondente/operacional/'
      path: '/'
      fullPath: '/correspondente/operacional/'
      preLoaderRoute: typeof CorrespondenteOperacionalIndexRouteImport
      parentRoute: typeof CorrespondenteOperacionalRoute
    }
    '/correspondente/crm/': {
      id: '/correspondente/crm/'
      path: '/'
      fullPath: '/correspondente/crm/'
      preLoaderRoute: typeof CorrespondenteCrmIndexRouteImport
      parentRoute: typeof CorrespondenteCrmRoute
    }
    '/corretor/operacional/simulacoes': {
      id: '/corretor/operacional/simulacoes'
      path: '/simulacoes'
      fullPath: '/corretor/operacional/simulacoes'
      preLoaderRoute: typeof CorretorOperacionalSimulacoesRouteImport
      parentRoute: typeof CorretorOperacionalRoute
    }
    '/corretor/operacional/minhas-simulacoes': {
      id: '/corretor/operacional/minhas-simulacoes'
      path: '/minhas-simulacoes'
      fullPath: '/corretor/operacional/minhas-simulacoes'
      preLoaderRoute: typeof CorretorOperacionalMinhasSimulacoesRouteImport
      parentRoute: typeof CorretorOperacionalRoute
    }
    '/corretor/operacional/consultas': {
      id: '/corretor/operacional/consultas'
      path: '/consultas'
      fullPath: '/corretor/operacional/consultas'
      preLoaderRoute: typeof CorretorOperacionalConsultasRouteImport
      parentRoute: typeof CorretorOperacionalRoute
    }
    '/corretor/crm/relatorios': {
      id: '/corretor/crm/relatorios'
      path: '/relatorios'
      fullPath: '/corretor/crm/relatorios'
      preLoaderRoute: typeof CorretorCrmRelatoriosRouteImport
      parentRoute: typeof CorretorCrmRoute
    }
    '/corretor/crm/consultas': {
      id: '/corretor/crm/consultas'
      path: '/consultas'
      fullPath: '/corretor/crm/consultas'
      preLoaderRoute: typeof CorretorCrmConsultasRouteImport
      parentRoute: typeof CorretorCrmRoute
    }
    '/corretor/crm/cadastro': {
      id: '/corretor/crm/cadastro'
      path: '/cadastro'
      fullPath: '/corretor/crm/cadastro'
      preLoaderRoute: typeof CorretorCrmCadastroRouteImport
      parentRoute: typeof CorretorCrmRoute
    }
    '/correspondente/operacional/simulacoes': {
      id: '/correspondente/operacional/simulacoes'
      path: '/simulacoes'
      fullPath: '/correspondente/operacional/simulacoes'
      preLoaderRoute: typeof CorrespondenteOperacionalSimulacoesRouteImport
      parentRoute: typeof CorrespondenteOperacionalRoute
    }
    '/correspondente/operacional/minhas-simulacoes': {
      id: '/correspondente/operacional/minhas-simulacoes'
      path: '/minhas-simulacoes'
      fullPath: '/correspondente/operacional/minhas-simulacoes'
      preLoaderRoute: typeof CorrespondenteOperacionalMinhasSimulacoesRouteImport
      parentRoute: typeof CorrespondenteOperacionalRoute
    }
    '/correspondente/operacional/consultas': {
      id: '/correspondente/operacional/consultas'
      path: '/consultas'
      fullPath: '/correspondente/operacional/consultas'
      preLoaderRoute: typeof CorrespondenteOperacionalConsultasRouteImport
      parentRoute: typeof CorrespondenteOperacionalRoute
    }
    '/correspondente/crm/relatorios': {
      id: '/correspondente/crm/relatorios'
      path: '/relatorios'
      fullPath: '/correspondente/crm/relatorios'
      preLoaderRoute: typeof CorrespondenteCrmRelatoriosRouteImport
      parentRoute: typeof CorrespondenteCrmRoute
    }
    '/correspondente/crm/consultas': {
      id: '/correspondente/crm/consultas'
      path: '/consultas'
      fullPath: '/correspondente/crm/consultas'
      preLoaderRoute: typeof CorrespondenteCrmConsultasRouteImport
      parentRoute: typeof CorrespondenteCrmRoute
    }
    '/correspondente/crm/cadastro': {
      id: '/correspondente/crm/cadastro'
      path: '/cadastro'
      fullPath: '/correspondente/crm/cadastro'
      preLoaderRoute: typeof CorrespondenteCrmCadastroRouteImport
      parentRoute: typeof CorrespondenteCrmRoute
    }
  }
}

interface ClienteRouteChildren {
  ClienteIndexRoute: typeof ClienteIndexRoute
}

const ClienteRouteChildren: ClienteRouteChildren = {
  ClienteIndexRoute: ClienteIndexRoute,
}

const ClienteRouteWithChildren =
  ClienteRoute._addFileChildren(ClienteRouteChildren)

interface CorrespondenteCrmRouteChildren {
  CorrespondenteCrmCadastroRoute: typeof CorrespondenteCrmCadastroRoute
  CorrespondenteCrmConsultasRoute: typeof CorrespondenteCrmConsultasRoute
  CorrespondenteCrmRelatoriosRoute: typeof CorrespondenteCrmRelatoriosRoute
  CorrespondenteCrmIndexRoute: typeof CorrespondenteCrmIndexRoute
}

const CorrespondenteCrmRouteChildren: CorrespondenteCrmRouteChildren = {
  CorrespondenteCrmCadastroRoute: CorrespondenteCrmCadastroRoute,
  CorrespondenteCrmConsultasRoute: CorrespondenteCrmConsultasRoute,
  CorrespondenteCrmRelatoriosRoute: CorrespondenteCrmRelatoriosRoute,
  CorrespondenteCrmIndexRoute: CorrespondenteCrmIndexRoute,
}

const CorrespondenteCrmRouteWithChildren =
  CorrespondenteCrmRoute._addFileChildren(CorrespondenteCrmRouteChildren)

interface CorrespondenteOperacionalRouteChildren {
  CorrespondenteOperacionalConsultasRoute: typeof CorrespondenteOperacionalConsultasRoute
  CorrespondenteOperacionalMinhasSimulacoesRoute: typeof CorrespondenteOperacionalMinhasSimulacoesRoute
  CorrespondenteOperacionalSimulacoesRoute: typeof CorrespondenteOperacionalSimulacoesRoute
  CorrespondenteOperacionalIndexRoute: typeof CorrespondenteOperacionalIndexRoute
}

const CorrespondenteOperacionalRouteChildren: CorrespondenteOperacionalRouteChildren =
  {
    CorrespondenteOperacionalConsultasRoute:
      CorrespondenteOperacionalConsultasRoute,
    CorrespondenteOperacionalMinhasSimulacoesRoute:
      CorrespondenteOperacionalMinhasSimulacoesRoute,
    CorrespondenteOperacionalSimulacoesRoute:
      CorrespondenteOperacionalSimulacoesRoute,
    CorrespondenteOperacionalIndexRoute: CorrespondenteOperacionalIndexRoute,
  }

const CorrespondenteOperacionalRouteWithChildren =
  CorrespondenteOperacionalRoute._addFileChildren(
    CorrespondenteOperacionalRouteChildren,
  )

interface CorrespondenteRouteChildren {
  CorrespondenteCrmRoute: typeof CorrespondenteCrmRouteWithChildren
  CorrespondenteOperacionalRoute: typeof CorrespondenteOperacionalRouteWithChildren
  CorrespondenteIndexRoute: typeof CorrespondenteIndexRoute
}

const CorrespondenteRouteChildren: CorrespondenteRouteChildren = {
  CorrespondenteCrmRoute: CorrespondenteCrmRouteWithChildren,
  CorrespondenteOperacionalRoute: CorrespondenteOperacionalRouteWithChildren,
  CorrespondenteIndexRoute: CorrespondenteIndexRoute,
}

const CorrespondenteRouteWithChildren = CorrespondenteRoute._addFileChildren(
  CorrespondenteRouteChildren,
)

interface CorretorCrmRouteChildren {
  CorretorCrmCadastroRoute: typeof CorretorCrmCadastroRoute
  CorretorCrmConsultasRoute: typeof CorretorCrmConsultasRoute
  CorretorCrmRelatoriosRoute: typeof CorretorCrmRelatoriosRoute
  CorretorCrmIndexRoute: typeof CorretorCrmIndexRoute
}

const CorretorCrmRouteChildren: CorretorCrmRouteChildren = {
  CorretorCrmCadastroRoute: CorretorCrmCadastroRoute,
  CorretorCrmConsultasRoute: CorretorCrmConsultasRoute,
  CorretorCrmRelatoriosRoute: CorretorCrmRelatoriosRoute,
  CorretorCrmIndexRoute: CorretorCrmIndexRoute,
}

const CorretorCrmRouteWithChildren = CorretorCrmRoute._addFileChildren(
  CorretorCrmRouteChildren,
)

interface CorretorOperacionalRouteChildren {
  CorretorOperacionalConsultasRoute: typeof CorretorOperacionalConsultasRoute
  CorretorOperacionalMinhasSimulacoesRoute: typeof CorretorOperacionalMinhasSimulacoesRoute
  CorretorOperacionalSimulacoesRoute: typeof CorretorOperacionalSimulacoesRoute
  CorretorOperacionalIndexRoute: typeof CorretorOperacionalIndexRoute
}

const CorretorOperacionalRouteChildren: CorretorOperacionalRouteChildren = {
  CorretorOperacionalConsultasRoute: CorretorOperacionalConsultasRoute,
  CorretorOperacionalMinhasSimulacoesRoute:
    CorretorOperacionalMinhasSimulacoesRoute,
  CorretorOperacionalSimulacoesRoute: CorretorOperacionalSimulacoesRoute,
  CorretorOperacionalIndexRoute: CorretorOperacionalIndexRoute,
}

const CorretorOperacionalRouteWithChildren =
  CorretorOperacionalRoute._addFileChildren(CorretorOperacionalRouteChildren)

interface CorretorRouteChildren {
  CorretorCrmRoute: typeof CorretorCrmRouteWithChildren
  CorretorOperacionalRoute: typeof CorretorOperacionalRouteWithChildren
  CorretorIndexRoute: typeof CorretorIndexRoute
}

const CorretorRouteChildren: CorretorRouteChildren = {
  CorretorCrmRoute: CorretorCrmRouteWithChildren,
  CorretorOperacionalRoute: CorretorOperacionalRouteWithChildren,
  CorretorIndexRoute: CorretorIndexRoute,
}

const CorretorRouteWithChildren = CorretorRoute._addFileChildren(
  CorretorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClienteRoute: ClienteRouteWithChildren,
  CorrespondenteRoute: CorrespondenteRouteWithChildren,
  CorretorRoute: CorretorRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
